---
title: "Data Science in Python"
author: "Charles Ingulli"
date: "6/24/2020"
output: 
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Pandas data frames and manipulation 
NumbPy arrays and matrices
SciPy

matplotlib
seaborn  all for plotting

algorithmic such as
Scikit-learn has ml reg and classif 
Statsmodels


## Reading in data


```{python}
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
Auto = pd.read_csv(url, header = None)
Auto.head()
```


there are various formats

tsv csv json xlsx

```{python}
import pandas as pd
#data = ""
df = pd.read_csv(url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",header = None)
headers = ["symboling", "normalized-losses", "make", "fuel-type", "aspiration", 
           "num-of-doors", "body-style", "drive-wheels", "engine-location", 
           "wheel-base", "length", "width", "height", "curb-weight", 
           "engine-type", "num-of-cylinders", "engine-size", "fuel-system", 
           "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", 
           "city-mpg", "highway-mpg", "price"]
df.columns = headers
df.replace("?", np.nan, True)
df.dropna(subset=["price"], axis = 0, inplace = True)
df["price"] = df["price"].astype("int")

```



```{python}
df.head(10)
df.tail(10)
df.columns = ["col1","col2"]
```

```{python}
df.to_csv("C:User/Desktop")
```


## Summarizing  data

Operations are perfomed on columns 

```{python}
df["column"]
```



```{python}
df.dtypes()
df.describe() # for numeric only; excludes non-number
df.describe(include = "all")
df.info() # top & bottom 30 rows

```


## The Search for Missing Values

A missing value is a cell in a data set that does not have an entry. These are typically represented could be ? NA 0 


Fixing errors and finding what missing value should be 

You can drop data by dropping a variable with a lot of missing entries or deleting specific entries. This is not great because you lose information. 



```{python}

df.dropna(subset=["price"], axis=0)
# inplace = True will perform the operation on the existing data set
```

```{python}
df.replace(missing, new)
```


# Ancillary Topics

## Connecting to a Database



What is a DBMS?
What is an API call?

Application Programming Interface (API) is a set of functions that allow you to access certain service. 


Connect to database then run querey 

How does Python contact the DBMS with an API call?
```{python}
from dbmodule import connect

connection = connect("databasename", "username", "pswd")

cursor = connection.cursor()

cursor.execute("select * from mytable")
results = cursor.fetchall()

cursor.close()
connection.close()


```


## Exploratory Data Analysis

Is a learning experience in 

An exploration of the data to learn more about it.


### Descriptive Statistics



Your mins your maxes your means and quartiles

Missing values are excluded from these statistics.


`value_counts()` will summarize categorical data. It is a method that can be applied to a categorical variable and will take the counts at each level. 



Box plots are a good way to look at the distribution of data

```{python}
import seaborn as sns
sns.boxplot(["A","B","C"],[1,2,3])
```


A Scatterplot is another good graphical tool for plotting data. These are especially good when both variables being plotted are quantitative variables. This is largely because these variables are number based and will also be refered to these as numerical variables.

```{python}
import matplotlib
matplotlib.pyplot.scatter([1,2,3,4],[5,6,7,8])
```


```{python}
import pandas as pd
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
df = pd.read_csv(url,header = None)
headers = ["symboling", "normalized-losses", "make", "fuel-type", "aspiration", 
           "num-of-doors", "body-style", "drive-wheels", "engine-location", 
           "wheel-base", "length", "width", "height", "curb-weight", 
           "engine-type", "num-of-cylinders", "engine-size", "fuel-system", 
           "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", 
           "city-mpg", "highway-mpg", "price"]
df.columns = headers
df.replace("?", np.nan, True)
df.dropna(subset=["price"], axis = 0, inplace = True)
df["price"] = df["price"].astype("int")



```


```{python}
y=df["price"]
x=df["engine-size"]
plt.pyplot.scatter(x, y)
plt.pyplot.title("Scatterplot of Engine Size vs Price")
plt.pyplot.xlabel("Engine Size")
plt.pyplot.ylabel("Price")
```

## Groups


In data science, you may want to look at summary statistics for different levels of a categorical level. We can do this by first grouping then data then applying our summary statistics methods.



`.pivot()` method will transpose the data to a different format. If data is displayed along the rows then we can display it along the columns and vice versa.



```{python}
df_grp = df[["drive-wheels","body-style","price"]].groupby(["drive-wheels","body-style"],as_index = False).mean()
print(df_grp)
```


```{python}
df_pivot=df_grp.pivot(index = "drive-wheels", columns = "body-style")
print(df_pivot)
```


HEATMAPPPSSSS


```{python}
import matplotlib as plt
plt.pyplot.pcolor(df_pivot, cmap = "RdBu")
plt.pyplot.colorbar()
plt.pyplot.show()
```


